# Generated by Django 6.0.4 on 2026-04-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_passwordresetcode_ticketorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_color',
            field=models.CharField(blank=True, help_text='Example: #e10600', max_length=20),
        ),
    ]
