# Generated by Django 6.0.4 on 2026-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_team_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='birthplace',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dnfs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='grand_prix_entered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='highest_grid_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='highest_race_finish',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='podiums',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='pole_positions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='world_championships',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
