# Generated by Django 6.0.4 on 2026-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homequicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
