# Generated by Django 6.0.4 on 2026-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_ticketorder_payment_id_ticketorder_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
