# Generated by Django 6.0.4 on 2026-04-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_driver_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='driver',
            name='initials',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
